import { test, expect } from "@playwright/test";

test("public deep links, assets, sample verification and responsive layout", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/login/");
  await page.getByText("Presentation workspaces", { exact: true }).click();
  await page.getByRole("button", { name: "Enter candidate demo" }).click();
  await expect(page).toHaveURL(/\/candidate\/?$/);
  for (const path of ["/", "/diploma/", "/graded-exams/", "/basic-school/", "/about/", "/contact/", "/login/", "/signup/", "/roadmap/", "/candidate/", "/admin/", "/examiner/"]) {
    const response = await page.goto(path);
    expect(response?.status()).toBe(200);
    await expect(page.locator("h1")).toBeVisible();
    await expect.poll(() => page.locator("img").evaluateAll(images => images.every(image => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0))).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    if (["/", "/candidate/", "/admin/"].includes(path)) await page.screenshot({ path: info.outputPath(`${path.replaceAll("/", "") || "home"}.png`), fullPage: true });
  }
  await page.goto("/verify/?number=MUSON-DEMO-2026");
  await expect(page.getByRole("heading", { name: "Valid sample certificate" })).toBeVisible();
  await expect(page.getByRole("img", { name: /QR code/ })).toBeVisible();
  await page.getByLabel("Certificate number").fill("NOT-A-CERTIFICATE");
  await page.getByRole("button", { name: "Verify", exact: true }).click();
  await expect(page.getByText(/No record found/)).toBeVisible();
  for (const path of ["/demo/interval.wav", "/demo/notation.svg", "/demo/document.pdf", "/demo/performance.mp4"]) expect((await page.request.get(path)).status()).toBe(200);
  expect(errors).toEqual([]);
});

test("candidate sign-up, login, logout, return destination and local account reset", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/candidate/application/");
  await expect(page.getByRole("heading", { name: "Welcome back", exact: true })).toBeVisible();
  await expect(page).toHaveURL(/\/login\/?\?next=/);
  await page.screenshot({ path: info.outputPath("login.png"), fullPage: true });
  await page.getByRole("link", { name: "Create an account", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Create your account" })).toBeVisible();
  await page.getByLabel("Full name", { exact: true }).fill("Tola Bello");
  await page.getByLabel("Email address", { exact: true }).fill("TOLA@example.test");
  await page.getByLabel("Password", { exact: true }).fill("demo-password");
  await page.getByRole("button", { name: "Show password", exact: true }).click();
  await expect(page.getByLabel("Password", { exact: true })).toHaveAttribute("type", "text");
  await page.getByRole("button", { name: "Hide password", exact: true }).click();
  await page.getByLabel("Confirm password", { exact: true }).fill("not-matching");
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page.getByRole("form", { name: "Create account" }).getByRole("alert")).toContainText("Passwords do not match");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("signup.png"), fullPage: true });
  await page.getByLabel("Confirm password", { exact: true }).fill("demo-password");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(/\/candidate\/application\/?$/);
  await page.goto("/candidate/profile/");
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue("Tola Bello");
  await expect(page.getByLabel("Email address", { exact: true })).toHaveValue("tola@example.test");
  await page.getByLabel("Phone number").fill("08000000001");
  await page.getByLabel("Date of birth").fill("2004-03-01");
  await page.getByRole("button", { name: "Save profile" }).click();
  await page.reload();
  await expect(page.getByLabel("Phone number")).toHaveValue("08000000001");
  expect(await page.evaluate(() => localStorage.getItem("muson-demo-v1"))).not.toContain("demo-password");
  await page.getByRole("button", { name: "Log out", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Welcome back", exact: true })).toBeVisible();
  await page.goto("/candidate/profile/");
  await expect(page).toHaveURL(/\/login\/?\?next=/);
  await page.getByLabel("Email address", { exact: true }).fill("tola@example.test");
  await page.getByLabel("Password", { exact: true }).fill("wrong-password");
  await page.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page.getByRole("form", { name: "Log in", exact: true }).getByRole("alert")).toContainText("does not match");
  await page.getByLabel("Password", { exact: true }).fill("demo-password");
  await page.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page).toHaveURL(/\/candidate\/profile\/?$/);
  await expect(page.getByLabel("Phone number")).toHaveValue("08000000001");
  await page.goto("/signup/");
  await expect(page.getByText(/An account already exists/)).toBeVisible();
  await page.goto("/candidate/");
  await expect(page.getByRole("heading", { name: "Welcome back, Tola." })).toBeVisible();
  await page.getByRole("button", { name: "Log out", exact: true }).click();
  await page.getByRole("button", { name: "Forgot password?" }).click();
  page.once("dialog", dialog => dialog.dismiss());
  await page.getByRole("button", { name: "Reset demo account", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Welcome back", exact: true })).toBeVisible();
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Reset demo account", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Create your account" })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("muson-demo-v1")!).state.account)).toBeNull();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});